### PR TITLE
fixed it for html5

### PR DESCRIPTION
**Pull request by JonnycatMeow**
yay

### CODE REVIEW

**Comment by JonnycatMeow** [comment]
@FuseIsHere813 please merge it

**Comment by Sylveondev** [comment]
Huge L

**Comment by JonnycatMeow** [comment]
> Huge L

how is it a huge L

**Comment by br4dnblehh** [comment]
Massive L

**Comment by FuseIsHere813** [comment]
> @FuseIsHere813 please merge it

L merge, Windows better

**Pull request closed without merging**
