### PR TITLE
fixed vs Dave and Bambi for Mac (removed shaders)

### PR DESCRIPTION
**Pull request by Gothbr4dn**

### CODE REVIEW

**Comment by br4dnblehh** [comment]
Fixed

**Comment by ghost** [comment]
why you fucking deleted the shaders, that were one of the best things that vs dave had

**Comment by br4dnblehh** [comment]
because that makes it work on mac

**Comment by Jaduplex** [comment]
you coulda just used #if windows or some shit

**Comment by ghost** [comment]
this is not the original dave and bambi without its shaders i have made a pull request about this

**Review by FuseIsHere813 — CHANGES_REQUESTED** [review]
Shaders are included in Polygonized, Furiosity and Glitch. I suggest you re add them, for both, Windows and Mac.

**Comment by br4dnblehh** [comment]
ok

**Comment by ghost** [comment]
please close this pr

**Pull request closed without merging**
