### PR TITLE
Fix Shaders for Linux and Mac

### PR DESCRIPTION
**Pull request by 4EverNoobys**

### CODE REVIEW

**Comment by 4EverNoobys** [comment]
this might also fix mac os crashing

**Comment by ghost** [comment]
letts go bro

**Comment by ghost** [comment]
but if ya want i have my own shadertools if ya want to check it out it helps out fixing the shader crash no self promo https://lib.haxe.org/p/shadertools/

**Comment by JuniorNovoa1** [comment]
holy shit i just tested this, YOU LITERALLY FIXED CRASHING ON MACOS TO

**Comment by JuniorNovoa1** [comment]
btw STFU JONNYCAT NOBODY WANTS UR SHITTY STOLEN SHADERTOOLS

**Comment by ghost** [comment]
i wasn't talking to you

**Comment by ghost** [comment]
also why do you want beef with me

**Comment by JuniorNovoa1** [comment]
i don't lol its just don't take shit and call it ur own :P

**Review by ghost — APPROVED** [review]
this works please accept this

**Review by JuniorNovoa1 — APPROVED** [review]
works 100%

**Pull request merged**
